# -*- coding: utf-8 -*-
"""phishing_detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdNbmki0zv-lp8HahhzcJh2xgJeQHeDc

#1. AI 점수
"""

!pip install transformers torch scikit-learn sentencepiece tqdm

from google.colab import files
uploaded = files.upload()

filename = list(uploaded.keys())[0]

texts = []
labels = []

current_text = ""

with open(filename, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()

        if line == "":
            continue

        # 마지막 줄 (라벨 포함)
        if line.endswith(",0") or line.endswith(",1"):
            full_text = current_text + " " + line
            full_text = full_text.strip()

            text, label = full_text.rsplit(",", 1)

            texts.append(text)
            labels.append(int(label))

            current_text = ""
        else:
            current_text += " " + line

print("데이터 개수:", len(texts))

from sklearn.model_selection import train_test_split

train_texts, val_texts, train_labels, val_labels = train_test_split(
    texts, labels, test_size=0.1
)

import torch
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer, BertForSequenceClassification
from torch.optim import AdamW

tokenizer = BertTokenizer.from_pretrained("monologg/kobert")

class ScamDataset(Dataset):
    def __init__(self, texts, labels):
        self.texts = texts
        self.labels = labels

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoding = tokenizer(
            self.texts[idx],
            padding='max_length',
            truncation=True,
            max_length=128,
            return_tensors='pt'
        )

        return {
            'input_ids': encoding['input_ids'].squeeze(),
            'attention_mask': encoding['attention_mask'].squeeze(),
            'labels': torch.tensor(self.labels[idx], dtype=torch.long)
        }

train_loader = DataLoader(ScamDataset(train_texts, train_labels), batch_size=4, shuffle=True)
val_loader = DataLoader(ScamDataset(val_texts, val_labels), batch_size=4)

model = BertForSequenceClassification.from_pretrained(
    "monologg/kobert",
    num_labels=2
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

optimizer = AdamW(model.parameters(), lr=2e-5)

from tqdm import tqdm

for epoch in range(2):   # 처음은 2로 충분
    model.train()
    total_loss = 0

    for batch in tqdm(train_loader):
        optimizer.zero_grad()

        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )

        loss = outputs.loss
        total_loss += loss.item()

        loss.backward()
        optimizer.step()

    print(f"Epoch {epoch+1}, Loss: {total_loss}")

def predict(text):
    model.eval()

    encoding = tokenizer(
        text,
        return_tensors='pt',
        truncation=True,
        padding=True,
        max_length=128
    )

    input_ids = encoding['input_ids'].to(device)
    attention_mask = encoding['attention_mask'].to(device)

    with torch.no_grad():
        outputs = model(input_ids, attention_mask=attention_mask)

    probs = torch.softmax(outputs.logits, dim=1)
    return probs[0][1].item()

print(predict("엄마 나 급해 돈 좀 보내줘"))
print(predict("회의 자료 공유드립니다"))

ai_score = predict(text)

"""# 2. 키워드 점수"""

keywords = [
    "검찰", "경찰", "수사", "계좌", "동결", "인증번호",
    "앱 설치", "송금", "입금", "대포통장",
    "[Web]", "엄마", "아빠", "급해", "돈 보내",
    "결제되었습니다", "확인", "배송지 누락",
    "파일 설치", "영상 보내"
]

def keyword_score(text):
    score = 0

    for word in keywords:
        if word in text:
            score += 1

    return score / len(keywords)  # 0~1 정규화

keywords = {
    "검찰": 2,
    "경찰": 2,
    "인증번호": 3,
    "송금": 3,
    "돈 보내": 3,
    "파일 설치": 3,
    "급해": 2
}

def keyword_score(text):
    score = 0

    for word, weight in keywords.items():
        if word in text:
            score += weight

    return score / sum(keywords.values())

"""#3. 패턴점수"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

phishing_patterns = [
    "검찰입니다 계좌가 사용되었습니다",
    "인증번호 알려주세요",
    "돈 보내줄 수 있나요 급합니다",
    "파일 설치하세요",
    "배송지가 누락되었습니다"
]

vectorizer = TfidfVectorizer()
vectorizer.fit(phishing_patterns)

def pattern_score(text):
    text_vec = vectorizer.transform([text])
    pattern_vec = vectorizer.transform(phishing_patterns)

    similarity = cosine_similarity(text_vec, pattern_vec)

    return similarity.max()  # 가장 유사한 패턴 점수

"""#4. 최종 결합"""

import math

def final_score(text):
    ai = predict(text)
    pattern = pattern_score(text)
    keyword = keyword_score(text)

    # 가중치
    w1 = 0.4  # pattern
    w2 = 0.4  # AI
    w3 = 0.2  # keyword

    score = w1 * pattern + w2 * ai + w3 * keyword

    # 로지스틱 변환
    prob = 1 / (1 + math.exp(-score * 5))  # 스케일링

    return prob

test_cases = [
    "엄마 나 지금 폰 고장나서 연락 안돼 급하게 돈 좀 보내줘",
    "서울중앙지검입니다 고객님 명의 계좌가 범죄에 연루되어 확인이 필요합니다 인증번호 알려주세요",
    "오늘 회의 자료 정리해서 메일로 보냈습니다 확인 부탁드립니다",
    "택배는 오늘 출고 예정이며 내일 도착 예정입니다"
]

for t in test_cases:
    print("문장:", t)
    print("AI:", predict(t))
    print("패턴:", pattern_score(t))
    print("키워드:", keyword_score(t))
    print("최종:", final_score(t))
    print("-" * 50)